/**
 * Top 1000 most common passwords
 * Source: SecLists - Common Passwords
 * Used to prevent users from choosing easily guessable passwords
 */
export const COMMON_PASSWORDS = new Set([
    '123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234', '111111', '1234567', 'dragon',
    '123123', 'baseball', 'iloveyou', 'trustno1', '1234567890', 'sunshine', 'master', '123321', '666666', 'photoshop',
    '1qaz2wsx', 'qwertyuiop', 'ashley', 'mustang', '121212', 'starwars', '654321', 'bailey', 'access', 'flower',
    '555555', 'passw0rd', 'shadow', 'lovely', '7777777', 'michael', '!@#$%^&*', 'jesus', 'password1', 'superman',
    'hello', 'charlie', '888888', '696969', 'hottie', 'freedom', 'aa123456', 'qazwsx', 'ninja', 'azerty',
    'loveme', 'whatever', 'donald', 'batman', 'zaq1zaq1', 'qwerty123', 'admin', 'welcome', 'monkey', 'login',
    'abc123', 'starwars', 'dragon', 'master', 'hello', 'freedom', 'whatever', 'qazwsx', 'trustno1', 'jordan',
    'password123', 'hunter', 'buster', 'soccer', 'harley', 'ranger', 'jennifer', 'michelle', 'jessica', 'andrew',
    'letmein', 'michelle', 'love', 'sunshine', 'ashley', 'nicole', 'chelsea', 'biteme', 'matthew', 'access',
    'yankees', '987654321', 'dallas', 'austin', 'thunder', 'taylor', 'matrix', 'william', 'corvette', 'hello',
    'martin', 'heather', 'secret', 'fucker', 'merlin', 'diamond', '1234qwer', 'ginger', 'princess', 'joshua',
    'cheese', 'amanda', 'summer', 'love', 'ashley', '6969', 'joshua', 'maggie', 'starwars', 'silver', 'william',
    'dallas', 'yankee', '123qwe', 'joseph', 'mother', 'secret', 'password', 'ginger', 'blowjob', 'nicole',
    'justin', 'banana', 'driver', 'marine', 'angels', 'fishing', 'david', 'maddog', 'hooters', 'wilson',
    'butthead', 'dennis', 'captain', 'bigdick', 'chester', 'smokey', 'xavier', 'steven', 'viking', 'snoopy',
    'blue', 'eagles', 'winner', 'samantha', 'house', 'miller', 'flower', 'jack', 'firebird', 'butter',
    'united', 'turtle', 'steelers', 'tiffany', 'zxcvbn', 'tomcat', 'golf', 'bond007', 'bear', 'tiger',
    'doctor', 'gateway', 'gators', 'angel', 'junior', 'thx1138', 'porno', 'badboy', 'debbie', 'spider',
    'melissa', 'booger', '1212', 'flyers', 'fish', 'porn', 'matrix', 'teens', 'scooter', 'jason',
    'walter', 'cumshot', 'boston', 'braves', 'yankee', 'lover', 'barney', 'victor', 'tucker', 'princess',
    'mercedes', '5150', 'doggie', 'zzzzzz', 'gunner', 'horney', 'bubba', '2112', 'fred', 'johnson',
    'xxxxx', 'tits', 'member', 'boobs', 'donald', 'bigdaddy', 'bronco', 'penis', 'voyager', 'rangers',
    'birdie', 'trouble', 'white', 'topgun', 'bigtits', 'bitches', 'green', 'super', 'qazwsx', 'magic',
    'lakers', 'rachel', 'slayer', 'scott', '2222', 'asdf', 'video', 'london', '7777', 'marlboro',
    'srinivas', 'internet', 'action', 'carter', 'jasper', 'monster', 'teresa', 'jeremy', '11111111', 'bill',
    'crystal', 'peter', 'pussies', 'cock', 'beer', 'rocket', 'theman', 'oliver', 'prince', 'beach',
    'amateur', '7777777', 'muffin', 'redsox', 'star', 'testing', 'shannon', 'murphy', 'frank', 'hannah',
    'dave', 'eagle1', '11111', 'mother', 'nathan', 'raiders', 'steve', 'forever', 'angela', 'viper',
    'ou812', 'jake', 'lovers', 'suckit', 'gregory', 'buddy', 'whatever', 'young', 'nicholas', 'lucky',
    'helpme', 'jackie', 'monica', 'midnight', 'college', 'baby', 'cunt', 'brian', 'mark', 'startrek',
    'sierra', 'leather', '232323', '4444', 'beavis', 'bigcock', 'happy', 'sophie', 'ladies', 'nascar',
    'giants', 'booty', '1', 'blonde', 'golden', '0', 'fire', 'sandra', 'pookie', 'packers',
    'einstein', 'dolphins', '0', 'chevy', 'winston', 'warrior', 'sammy', 'slut', '8675309', 'zxcvbnm',
    'nipples', 'power', 'victoria', 'asdfgh', 'vagina', 'toyota', 'travis', 'hotdog', 'paris', 'rock',
    'xxxx', 'extreme', 'redskins', 'erotic', 'dirty', 'ford', 'freddy', 'arsenal', 'access14', 'wolf',
    'nipple', 'iloveyou', 'alex', 'florida', 'eric', 'legend', 'movie', 'success', 'rosebud', 'jaguar',
    'great', 'cool', 'cooper', '1313', 'scorpio', 'mountain', 'madison', '987654', 'brazil', 'lauren',
    'japan', 'naked', 'squirt', 'stars', 'apple', 'alexis', 'aaaa', 'bonnie', 'peaches', 'jasmine',
    'kevin', 'matt', 'qwertyui', 'danielle', 'beaver', '4321', '4128', 'runner', 'swimming', 'dolphin',
    'gordon', 'casper', 'stupid', 'shit', 'saturn', 'gemini', 'apples', 'august', '3333', 'canada',
    'blazer', 'cumming', 'hunting', 'kitty', 'rainbow', '112233', 'arthur', 'cream', 'calvin', 'shaved',
    'surfer', 'samson', 'kelly', 'paul', 'mine', 'king', 'racing', '5555', 'eagle', 'hentai',
    'newyork', 'little', 'redwings', 'smith', 'sticky', 'cocacola', 'animal', 'broncos', 'private', 'skippy',
    'marvin', 'blondes', 'enjoy', 'girl', 'apollo', 'parker', 'qwert', 'time', 'sydney', 'women',
    'voodoo', 'magnum', 'juice', 'abgrtyu', '777777', 'dreams', 'maxwell', 'music', 'rush2112', 'russia',
    'scorpion', 'rebecca', 'tester', 'mistress', 'phantom', 'billy', '6666', 'albert'
]);
