// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EnumActivityLogsSeverity string

const (
	EnumActivityLogsSeverityLow      EnumActivityLogsSeverity = "low"
	EnumActivityLogsSeverityMedium   EnumActivityLogsSeverity = "medium"
	EnumActivityLogsSeverityHigh     EnumActivityLogsSeverity = "high"
	EnumActivityLogsSeverityCritical EnumActivityLogsSeverity = "critical"
)

func (e *EnumActivityLogsSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumActivityLogsSeverity(s)
	case string:
		*e = EnumActivityLogsSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumActivityLogsSeverity: %T", src)
	}
	return nil
}

type NullEnumActivityLogsSeverity struct {
	EnumActivityLogsSeverity EnumActivityLogsSeverity `json:"enum_ActivityLogs_severity"`
	Valid                    bool                     `json:"valid"` // Valid is true if EnumActivityLogsSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumActivityLogsSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.EnumActivityLogsSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumActivityLogsSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumActivityLogsSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumActivityLogsSeverity), nil
}

type EnumActivityLogsStatus string

const (
	EnumActivityLogsStatusSuccess EnumActivityLogsStatus = "success"
	EnumActivityLogsStatusFailure EnumActivityLogsStatus = "failure"
)

func (e *EnumActivityLogsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumActivityLogsStatus(s)
	case string:
		*e = EnumActivityLogsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumActivityLogsStatus: %T", src)
	}
	return nil
}

type NullEnumActivityLogsStatus struct {
	EnumActivityLogsStatus EnumActivityLogsStatus `json:"enum_ActivityLogs_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if EnumActivityLogsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumActivityLogsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumActivityLogsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumActivityLogsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumActivityLogsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumActivityLogsStatus), nil
}

type EnumArcoRequestsRequestType string

const (
	EnumArcoRequestsRequestTypeAccess        EnumArcoRequestsRequestType = "access"
	EnumArcoRequestsRequestTypeRectification EnumArcoRequestsRequestType = "rectification"
	EnumArcoRequestsRequestTypeCancellation  EnumArcoRequestsRequestType = "cancellation"
	EnumArcoRequestsRequestTypeOpposition    EnumArcoRequestsRequestType = "opposition"
)

func (e *EnumArcoRequestsRequestType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumArcoRequestsRequestType(s)
	case string:
		*e = EnumArcoRequestsRequestType(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumArcoRequestsRequestType: %T", src)
	}
	return nil
}

type NullEnumArcoRequestsRequestType struct {
	EnumArcoRequestsRequestType EnumArcoRequestsRequestType `json:"enum_ArcoRequests_requestType"`
	Valid                       bool                        `json:"valid"` // Valid is true if EnumArcoRequestsRequestType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumArcoRequestsRequestType) Scan(value interface{}) error {
	if value == nil {
		ns.EnumArcoRequestsRequestType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumArcoRequestsRequestType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumArcoRequestsRequestType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumArcoRequestsRequestType), nil
}

type EnumArcoRequestsStatus string

const (
	EnumArcoRequestsStatusPending    EnumArcoRequestsStatus = "pending"
	EnumArcoRequestsStatusInProgress EnumArcoRequestsStatus = "in_progress"
	EnumArcoRequestsStatusCompleted  EnumArcoRequestsStatus = "completed"
	EnumArcoRequestsStatusRejected   EnumArcoRequestsStatus = "rejected"
)

func (e *EnumArcoRequestsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumArcoRequestsStatus(s)
	case string:
		*e = EnumArcoRequestsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumArcoRequestsStatus: %T", src)
	}
	return nil
}

type NullEnumArcoRequestsStatus struct {
	EnumArcoRequestsStatus EnumArcoRequestsStatus `json:"enum_ArcoRequests_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if EnumArcoRequestsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumArcoRequestsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumArcoRequestsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumArcoRequestsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumArcoRequestsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumArcoRequestsStatus), nil
}

type EnumUsersRole string

const (
	EnumUsersRoleRoot     EnumUsersRole = "root"
	EnumUsersRoleAdmin    EnumUsersRole = "admin"
	EnumUsersRoleOperador EnumUsersRole = "operador"
	EnumUsersRoleAuditor  EnumUsersRole = "auditor"
	EnumUsersRoleDemo     EnumUsersRole = "demo"
)

func (e *EnumUsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumUsersRole(s)
	case string:
		*e = EnumUsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumUsersRole: %T", src)
	}
	return nil
}

type NullEnumUsersRole struct {
	EnumUsersRole EnumUsersRole `json:"enum_Users_role"`
	Valid         bool          `json:"valid"` // Valid is true if EnumUsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.EnumUsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumUsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumUsersRole), nil
}

type EnumVisitsAction string

const (
	EnumVisitsActionCarga    EnumVisitsAction = "Carga"
	EnumVisitsActionDescarga EnumVisitsAction = "Descarga"
	EnumVisitsActionNinguna  EnumVisitsAction = "Ninguna"
)

func (e *EnumVisitsAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumVisitsAction(s)
	case string:
		*e = EnumVisitsAction(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumVisitsAction: %T", src)
	}
	return nil
}

type NullEnumVisitsAction struct {
	EnumVisitsAction EnumVisitsAction `json:"enum_Visits_action"`
	Valid            bool             `json:"valid"` // Valid is true if EnumVisitsAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumVisitsAction) Scan(value interface{}) error {
	if value == nil {
		ns.EnumVisitsAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumVisitsAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumVisitsAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumVisitsAction), nil
}

type EnumVisitsStatus string

const (
	EnumVisitsStatusWaiting      EnumVisitsStatus = "waiting"
	EnumVisitsStatusActive       EnumVisitsStatus = "active"
	EnumVisitsStatusIntermittent EnumVisitsStatus = "intermittent"
	EnumVisitsStatusCompleted    EnumVisitsStatus = "completed"
)

func (e *EnumVisitsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumVisitsStatus(s)
	case string:
		*e = EnumVisitsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumVisitsStatus: %T", src)
	}
	return nil
}

type NullEnumVisitsStatus struct {
	EnumVisitsStatus EnumVisitsStatus `json:"enum_Visits_status"`
	Valid            bool             `json:"valid"` // Valid is true if EnumVisitsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumVisitsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumVisitsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumVisitsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumVisitsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumVisitsStatus), nil
}

type ActivityLog struct {
	ID         int32              `json:"id"`
	UserId     int32              `json:"userId"`
	Username   string             `json:"username"`
	Action     string             `json:"action"`
	Entity     string             `json:"entity"`
	EntityId   string             `json:"entityId"`
	Details    pgtype.Text        `json:"details"`
	IpAddress  pgtype.Text        `json:"ipAddress"`
	UserAgent  pgtype.Text        `json:"userAgent"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	StatusCode pgtype.Int4        `json:"statusCode"`
	Duration   pgtype.Int4        `json:"duration"`
	Severity   pgtype.Text        `json:"severity"`
	Role       pgtype.Text        `json:"role"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceId pgtype.Int4        `json:"resourceId"`
	Status     pgtype.Text        `json:"status"`
}

type ArcoRequest struct {
	ID                     int32                       `json:"id"`
	RequestType            EnumArcoRequestsRequestType `json:"requestType"`
	SubjectCedulaHash      string                      `json:"subjectCedulaHash"`
	SubjectCedulaEncrypted pgtype.Text                 `json:"subjectCedulaEncrypted"`
	RequestedByName        string                      `json:"requestedByName"`
	RequestedByUserId      pgtype.Int4                 `json:"requestedByUserId"`
	ContactEmail           pgtype.Text                 `json:"contactEmail"`
	Reason                 pgtype.Text                 `json:"reason"`
	RequestPayload         pgtype.Text                 `json:"requestPayload"`
	Status                 EnumArcoRequestsStatus      `json:"status"`
	ResolutionNotes        pgtype.Text                 `json:"resolutionNotes"`
	ResolvedAt             pgtype.Timestamptz          `json:"resolvedAt"`
	CreatedAt              pgtype.Timestamptz          `json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz          `json:"updatedAt"`
}

type Department struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Code      pgtype.Text      `json:"code"`
	IsActive  pgtype.Bool      `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type IntermittentLog struct {
	ID           int32              `json:"id"`
	VisitID      int32              `json:"visit_id"`
	CheckOut     pgtype.Timestamptz `json:"check_out"`
	ReEntry      pgtype.Timestamptz `json:"re_entry"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	RegisteredBy pgtype.Text        `json:"registered_by"`
	ReenteredBy  pgtype.Text        `json:"reentered_by"`
}

type SequelizeMetum struct {
	Name string `json:"name"`
}

type User struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	Email              pgtype.Text        `json:"email"`
	TokenVersion       int32              `json:"tokenVersion"`
	Password           string             `json:"password"`
	Role               NullEnumUsersRole  `json:"role"`
	ResetToken         pgtype.Text        `json:"resetToken"`
	ResetTokenExpiry   pgtype.Timestamptz `json:"resetTokenExpiry"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	MustChangePassword pgtype.Bool        `json:"mustChangePassword"`
	PasswordChangedAt  pgtype.Timestamptz `json:"passwordChangedAt"`
	LoginAttempts      pgtype.Int4        `json:"loginAttempts"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
}

type Visit struct {
	ID                   int32                `json:"id"`
	VisitorCedula        string               `json:"visitor_cedula"`
	Purpose              string               `json:"purpose"`
	PersonToVisit        string               `json:"person_to_visit"`
	CheckInTime          pgtype.Timestamptz   `json:"check_in_time"`
	CheckOutTime         pgtype.Timestamptz   `json:"check_out_time"`
	Status               NullEnumVisitsStatus `json:"status"`
	Notes                pgtype.Text          `json:"notes"`
	CompanionName        pgtype.Text          `json:"companion_name"`
	CompanionCedula      pgtype.Text          `json:"companion_cedula"`
	VehicleBrand         pgtype.Text          `json:"vehicle_brand"`
	VehicleModel         pgtype.Text          `json:"vehicle_model"`
	VehiclePlate         pgtype.Text          `json:"vehicle_plate"`
	Area                 pgtype.Text          `json:"area"`
	Action               NullEnumVisitsAction `json:"action"`
	Department           pgtype.Text          `json:"department"`
	CreatedAt            pgtype.Timestamptz   `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz   `json:"updatedAt"`
	VisitorID            pgtype.Int4          `json:"visitor_id"`
	ArrivalTime          pgtype.Timestamptz   `json:"arrival_time"`
	EntryTime            pgtype.Timestamptz   `json:"entry_time"`
	ExitTime             pgtype.Timestamptz   `json:"exit_time"`
	TargetDepartment     pgtype.Text          `json:"target_department"`
	HostPerson           pgtype.Text          `json:"host_person"`
	ConsentPolicyVersion pgtype.Text          `json:"consent_policy_version"`
	ConsentAcceptedAt    pgtype.Timestamptz   `json:"consent_accepted_at"`
	ConsentRecordedBy    pgtype.Int4          `json:"consent_recorded_by"`
}

type VisitPurpose struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	IsActive  pgtype.Bool      `json:"isActive"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Visitor struct {
	ID              int32              `json:"id"`
	AnonymizedAt    pgtype.Timestamptz `json:"anonymizedAt"`
	Cedula          string             `json:"cedula"`
	EncryptedCedula pgtype.Text        `json:"encrypted_cedula"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Company         string             `json:"company"`
	JobTitle        pgtype.Text        `json:"job_title"`
	PhotoUrl        pgtype.Text        `json:"photo_url"`
	IDPhotoUrl      pgtype.Text        `json:"id_photo_url"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	PhotoData       []byte             `json:"photo_data"`
	IDPhotoData     []byte             `json:"id_photo_data"`
	IsBlocked       pgtype.Bool        `json:"isBlocked"`
	Observations    pgtype.Text        `json:"observations"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type VisitorEditHistory struct {
	ID               int32              `json:"id"`
	VisitId          pgtype.Int4        `json:"visitId"`
	VisitorId        int32              `json:"visitorId"`
	Field            string             `json:"field"`
	OldValue         pgtype.Text        `json:"oldValue"`
	NewValue         pgtype.Text        `json:"newValue"`
	EditedBy         int32              `json:"editedBy"`
	EditedByUsername string             `json:"editedByUsername"`
	EditedAt         pgtype.Timestamptz `json:"editedAt"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}
