// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changePassword = `-- name: ChangePassword :execrows
UPDATE "Users" SET password=$2,"mustChangePassword"=$3,"passwordChangedAt"=now(),"tokenVersion"="tokenVersion"+1,"resetToken"=null,"resetTokenExpiry"=null,"loginAttempts"=0,"lockedUntil"=null,"updatedAt"=now() WHERE id=$1 AND "tokenVersion"=$4
`

type ChangePasswordParams struct {
	ID                 int32       `json:"id"`
	Password           string      `json:"password"`
	MustChangePassword pgtype.Bool `json:"mustChangePassword"`
	TokenVersion       int32       `json:"tokenVersion"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, changePassword,
		arg.ID,
		arg.Password,
		arg.MustChangePassword,
		arg.TokenVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeResetToken = `-- name: ConsumeResetToken :one
UPDATE "Users" SET password=$2,"resetToken"=null,"resetTokenExpiry"=null,"mustChangePassword"=false,"passwordChangedAt"=now(),"tokenVersion"="tokenVersion"+1,"loginAttempts"=0,"lockedUntil"=null,"updatedAt"=now() WHERE "resetToken"=$1 AND "resetTokenExpiry">now() RETURNING id,username,role::text AS role
`

type ConsumeResetTokenParams struct {
	ResetToken pgtype.Text `json:"resetToken"`
	Password   string      `json:"password"`
}

type ConsumeResetTokenRow struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) ConsumeResetToken(ctx context.Context, arg ConsumeResetTokenParams) (ConsumeResetTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeResetToken, arg.ResetToken, arg.Password)
	var i ConsumeResetTokenRow
	err := row.Scan(&i.ID, &i.Username, &i.Role)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT id,username,password,COALESCE(role::text,'operador')::text AS role,email,"tokenVersion",COALESCE("mustChangePassword",true) AS must_change_password,COALESCE("loginAttempts",0) AS login_attempts,"lockedUntil" FROM "Users" WHERE username=$1
`

type FindUserRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	Password           string             `json:"password"`
	Role               string             `json:"role"`
	Email              pgtype.Text        `json:"email"`
	TokenVersion       int32              `json:"tokenVersion"`
	MustChangePassword bool               `json:"must_change_password"`
	LoginAttempts      int32              `json:"login_attempts"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) FindUser(ctx context.Context, username string) (FindUserRow, error) {
	row := q.db.QueryRow(ctx, findUser, username)
	var i FindUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Email,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.LoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id,username,password,COALESCE(role::text,'operador')::text AS role,email,"tokenVersion",COALESCE("mustChangePassword",true) AS must_change_password,COALESCE("loginAttempts",0) AS login_attempts,"lockedUntil" FROM "Users" WHERE id=$1
`

type FindUserByIDRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	Password           string             `json:"password"`
	Role               string             `json:"role"`
	Email              pgtype.Text        `json:"email"`
	TokenVersion       int32              `json:"tokenVersion"`
	MustChangePassword bool               `json:"must_change_password"`
	LoginAttempts      int32              `json:"login_attempts"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) FindUserByID(ctx context.Context, id int32) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Email,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.LoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const findVisit = `-- name: FindVisit :one
SELECT id, visitor_cedula, purpose, person_to_visit, check_in_time, check_out_time, status, notes, companion_name, companion_cedula, vehicle_brand, vehicle_model, vehicle_plate, area, action, department, "createdAt", "updatedAt", visitor_id, arrival_time, entry_time, exit_time, target_department, host_person, consent_policy_version, consent_accepted_at, consent_recorded_by FROM "Visits" WHERE id=$1
`

func (q *Queries) FindVisit(ctx context.Context, id int32) (Visit, error) {
	row := q.db.QueryRow(ctx, findVisit, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.VisitorCedula,
		&i.Purpose,
		&i.PersonToVisit,
		&i.CheckInTime,
		&i.CheckOutTime,
		&i.Status,
		&i.Notes,
		&i.CompanionName,
		&i.CompanionCedula,
		&i.VehicleBrand,
		&i.VehicleModel,
		&i.VehiclePlate,
		&i.Area,
		&i.Action,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitorID,
		&i.ArrivalTime,
		&i.EntryTime,
		&i.ExitTime,
		&i.TargetDepartment,
		&i.HostPerson,
		&i.ConsentPolicyVersion,
		&i.ConsentAcceptedAt,
		&i.ConsentRecordedBy,
	)
	return i, err
}

const findVisitor = `-- name: FindVisitor :one
SELECT id, "anonymizedAt", cedula, encrypted_cedula, first_name, last_name, company, job_title, photo_url, id_photo_url, email, phone, "updatedAt", photo_data, id_photo_data, "isBlocked", observations, "createdAt" FROM "Visitors" WHERE cedula=$1 AND "anonymizedAt" IS NULL
`

func (q *Queries) FindVisitor(ctx context.Context, cedula string) (Visitor, error) {
	row := q.db.QueryRow(ctx, findVisitor, cedula)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.AnonymizedAt,
		&i.Cedula,
		&i.EncryptedCedula,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.JobTitle,
		&i.PhotoUrl,
		&i.IDPhotoUrl,
		&i.Email,
		&i.Phone,
		&i.UpdatedAt,
		&i.PhotoData,
		&i.IDPhotoData,
		&i.IsBlocked,
		&i.Observations,
		&i.CreatedAt,
	)
	return i, err
}

const findVisitorByID = `-- name: FindVisitorByID :one
SELECT id, "anonymizedAt", cedula, encrypted_cedula, first_name, last_name, company, job_title, photo_url, id_photo_url, email, phone, "updatedAt", photo_data, id_photo_data, "isBlocked", observations, "createdAt" FROM "Visitors" WHERE id=$1
`

func (q *Queries) FindVisitorByID(ctx context.Context, id int32) (Visitor, error) {
	row := q.db.QueryRow(ctx, findVisitorByID, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.AnonymizedAt,
		&i.Cedula,
		&i.EncryptedCedula,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.JobTitle,
		&i.PhotoUrl,
		&i.IDPhotoUrl,
		&i.Email,
		&i.Phone,
		&i.UpdatedAt,
		&i.PhotoData,
		&i.IDPhotoData,
		&i.IsBlocked,
		&i.Observations,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id,username,email,role::text AS role,"mustChangePassword","loginAttempts","lockedUntil" FROM "Users" ORDER BY id
`

type ListUsersRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	Email              pgtype.Text        `json:"email"`
	Role               string             `json:"role"`
	MustChangePassword pgtype.Bool        `json:"mustChangePassword"`
	LoginAttempts      pgtype.Int4        `json:"loginAttempts"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.MustChangePassword,
			&i.LoginAttempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id,username,password,COALESCE(role::text,'operador')::text AS role,email,"tokenVersion",COALESCE("mustChangePassword",true) AS must_change_password,COALESCE("loginAttempts",0) AS login_attempts,"lockedUntil" FROM "Users" WHERE username=$1 FOR UPDATE
`

type LockUserRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	Password           string             `json:"password"`
	Role               string             `json:"role"`
	Email              pgtype.Text        `json:"email"`
	TokenVersion       int32              `json:"tokenVersion"`
	MustChangePassword bool               `json:"must_change_password"`
	LoginAttempts      int32              `json:"login_attempts"`
	LockedUntil        pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) LockUser(ctx context.Context, username string) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, username)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Email,
		&i.TokenVersion,
		&i.MustChangePassword,
		&i.LoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const lockVisit = `-- name: LockVisit :one
SELECT id, visitor_cedula, purpose, person_to_visit, check_in_time, check_out_time, status, notes, companion_name, companion_cedula, vehicle_brand, vehicle_model, vehicle_plate, area, action, department, "createdAt", "updatedAt", visitor_id, arrival_time, entry_time, exit_time, target_department, host_person, consent_policy_version, consent_accepted_at, consent_recorded_by FROM "Visits" WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockVisit(ctx context.Context, id int32) (Visit, error) {
	row := q.db.QueryRow(ctx, lockVisit, id)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.VisitorCedula,
		&i.Purpose,
		&i.PersonToVisit,
		&i.CheckInTime,
		&i.CheckOutTime,
		&i.Status,
		&i.Notes,
		&i.CompanionName,
		&i.CompanionCedula,
		&i.VehicleBrand,
		&i.VehicleModel,
		&i.VehiclePlate,
		&i.Area,
		&i.Action,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisitorID,
		&i.ArrivalTime,
		&i.EntryTime,
		&i.ExitTime,
		&i.TargetDepartment,
		&i.HostPerson,
		&i.ConsentPolicyVersion,
		&i.ConsentAcceptedAt,
		&i.ConsentRecordedBy,
	)
	return i, err
}

const lockVisitor = `-- name: LockVisitor :one
SELECT id, "anonymizedAt", cedula, encrypted_cedula, first_name, last_name, company, job_title, photo_url, id_photo_url, email, phone, "updatedAt", photo_data, id_photo_data, "isBlocked", observations, "createdAt" FROM "Visitors" WHERE cedula=$1 AND "anonymizedAt" IS NULL FOR UPDATE
`

func (q *Queries) LockVisitor(ctx context.Context, cedula string) (Visitor, error) {
	row := q.db.QueryRow(ctx, lockVisitor, cedula)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.AnonymizedAt,
		&i.Cedula,
		&i.EncryptedCedula,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.JobTitle,
		&i.PhotoUrl,
		&i.IDPhotoUrl,
		&i.Email,
		&i.Phone,
		&i.UpdatedAt,
		&i.PhotoData,
		&i.IDPhotoData,
		&i.IsBlocked,
		&i.Observations,
		&i.CreatedAt,
	)
	return i, err
}

const loginFailed = `-- name: LoginFailed :exec
UPDATE "Users" SET "loginAttempts"=$2,"lockedUntil"=$3,"updatedAt"=now() WHERE id=$1
`

type LoginFailedParams struct {
	ID            int32              `json:"id"`
	LoginAttempts pgtype.Int4        `json:"loginAttempts"`
	LockedUntil   pgtype.Timestamptz `json:"lockedUntil"`
}

func (q *Queries) LoginFailed(ctx context.Context, arg LoginFailedParams) error {
	_, err := q.db.Exec(ctx, loginFailed, arg.ID, arg.LoginAttempts, arg.LockedUntil)
	return err
}

const loginSucceeded = `-- name: LoginSucceeded :exec
UPDATE "Users" SET "loginAttempts"=0,"lockedUntil"=null,"updatedAt"=now() WHERE id=$1
`

func (q *Queries) LoginSucceeded(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, loginSucceeded, id)
	return err
}

const saveResetToken = `-- name: SaveResetToken :exec
UPDATE "Users" SET "resetToken"=$2,"resetTokenExpiry"=$3,"updatedAt"=now() WHERE id=$1
`

type SaveResetTokenParams struct {
	ID               int32              `json:"id"`
	ResetToken       pgtype.Text        `json:"resetToken"`
	ResetTokenExpiry pgtype.Timestamptz `json:"resetTokenExpiry"`
}

func (q *Queries) SaveResetToken(ctx context.Context, arg SaveResetTokenParams) error {
	_, err := q.db.Exec(ctx, saveResetToken, arg.ID, arg.ResetToken, arg.ResetTokenExpiry)
	return err
}

const visitLogs = `-- name: VisitLogs :many
SELECT id, visit_id, check_out, re_entry, notes, "createdAt", "updatedAt", registered_by, reentered_by FROM "IntermittentLogs" WHERE visit_id=$1 ORDER BY check_out
`

func (q *Queries) VisitLogs(ctx context.Context, visitID int32) ([]IntermittentLog, error) {
	rows, err := q.db.Query(ctx, visitLogs, visitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntermittentLog
	for rows.Next() {
		var i IntermittentLog
		if err := rows.Scan(
			&i.ID,
			&i.VisitID,
			&i.CheckOut,
			&i.ReEntry,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegisteredBy,
			&i.ReenteredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAudit = `-- name: WriteAudit :exec
INSERT INTO "ActivityLogs"("userId",username,action,entity,"entityId",details,"ipAddress","userAgent","createdAt",role,method,path,status,"statusCode") VALUES($1,$2,$3,$4,$5,$6,$7,$8,now(),$9,$10,$11,'success',200)
`

type WriteAuditParams struct {
	UserId    int32       `json:"userId"`
	Username  string      `json:"username"`
	Action    string      `json:"action"`
	Entity    string      `json:"entity"`
	EntityId  string      `json:"entityId"`
	Details   pgtype.Text `json:"details"`
	IpAddress pgtype.Text `json:"ipAddress"`
	UserAgent pgtype.Text `json:"userAgent"`
	Role      pgtype.Text `json:"role"`
	Method    pgtype.Text `json:"method"`
	Path      pgtype.Text `json:"path"`
}

func (q *Queries) WriteAudit(ctx context.Context, arg WriteAuditParams) error {
	_, err := q.db.Exec(ctx, writeAudit,
		arg.UserId,
		arg.Username,
		arg.Action,
		arg.Entity,
		arg.EntityId,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.Role,
		arg.Method,
		arg.Path,
	)
	return err
}
